
// Exported from: ../../storyharp-js/converted_source/usregistrationform.lfm

import { m } from "mithril"
import { caption } from "common"

export function viewRegistrationForm() {
    return m("RegistrationForm.TRegistrationForm",
        {
        // ActiveControl: "UserNameEdit",
        // BorderStyle: "bsDialog",
        // Caption: "Registration",
        // ClientHeight: "439",
        // ClientWidth: "561",
        // Font.Height: "-13",
        // Font.Name: "MS Sans Serif",
        // OnActivate: "FormActivate",
        // PixelsPerInch: "100",
        // Position: "poScreenCenter",
        // TextHeight: "16",
        // HorzScrollBar.Page: "560",
        // VertScrollBar.Page: "438",
        // Left: "492",
        // Height: "439",
        // Top: "209",
        // Width: "561",
        },
        m("span.Label1.TLabel",
            {
                // Color: "clNone",
                // ParentColor: "False",
                // Left: "48",
                // Height: "17",
                // Top: "268",
                // Width: "81",
            },
            "User name",
        ),
        m("span.Label2.TLabel",
            {
                // Color: "clNone",
                // ParentColor: "False",
                // Left: "12",
                // Height: "17",
                // Top: "304",
                // Width: "127",
            },
            "Registration code",
        ),
        m("span.DateInstalledLabel.TLabel",
            {
                // Color: "clNone",
                // ParentColor: "False",
                // Visible: "False",
                // Left: "20",
                // Height: "17",
                // Top: "232",
                // Width: "134",
            },
            "DateInstalledLabel",
        ),
        m("span.DaysSinceInstallationLabel.TLabel",
            {
                // Color: "clNone",
                // ParentColor: "False",
                // Visible: "False",
                // Left: "220",
                // Height: "17",
                // Top: "232",
                // Width: "193",
            },
            "DaysSinceInstallationLabel",
        ),
        m("input.UserNameEdit.TEdit",
            {
                // OnKeyPress: "UserNameEditKeyPress",
                // TabOrder: "0",
                // Left: "124",
                // Height: "24",
                // Top: "264",
                // Width: "217",
            },
        ),
        m("input.RegistrationCodeEdit.TEdit",
            {
                // OnKeyPress: "RegistrationCodeEditKeyPress",
                // TabOrder: "1",
                // Left: "124",
                // Height: "24",
                // Top: "300",
                // Width: "217",
            },
        ),
        m("button.OKButton.TButton",
            {
                onclick: OKButtonClick,
                // BorderSpacing.InnerBorder: "2",
                // TabOrder: "2",
                // Left: "408",
                // Height: "25",
                // Top: "308",
                // Width: "109",
            },
            "Register",
        ),
        m("button.CancelButton.TButton",
            {
                onclick: CancelButtonClick,
                // BorderSpacing.InnerBorder: "2",
                // TabOrder: "3",
                // Left: "412",
                // Height: "25",
                // Top: "228",
                // Width: "103",
            },
            "Cancel",
        ),
        m("textarea.DisplayMemo.TMemo",
            {
                // Lines.Strings: ["This fully functional evaluation copy may be used for evaluation purposes only.","If you use this software for purposes other than evaluation, ","you are legally required to register it. ","As a special exception, if you use a copy of this program ","only to play stories created by others, (such as using the /P command line ","option), you do not need to register that copy.","Under no circumstances are you licensed to distribute output created ","by an unregistered copy of this program.","This is a summary only. See the accompanying license.txt file for exact details."],
                // ReadOnly: "True",
                // TabOrder: "4",
                // Left: "16",
                // Height: "205",
                // Top: "12",
                // Width: "485",
            },
        ),
        m("button.EnableEditorButton.TButton",
            {
                onclick: EnableEditorButtonClick,
                // BorderSpacing.InnerBorder: "2",
                // TabOrder: "5",
                // Left: "408",
                // Height: "25",
                // Top: "276",
                // Width: "107",
            },
            "Enable editor",
        ),
        m("button.OnlineRegistrationButton.TButton",
            {
                onclick: OnlineRegistrationButtonClick,
                // BorderSpacing.InnerBorder: "2",
                // TabOrder: "6",
                // Left: "408",
                // Height: "25",
                // Top: "336",
                // Width: "109",
            },
            "Pay now online",
        ),
        m("button.AbortButton.TButton",
            {
                // BorderSpacing.InnerBorder: "2",
                // Enabled: "False",
                // TabOrder: "7",
                // Left: "324",
                // Height: "25",
                // Top: "336",
                // Width: "75",
            },
            "Abort",
        ),
    )
}

function CancelButtonClick() { console.log("CancelButtonClick") }

function EnableEditorButtonClick() { console.log("EnableEditorButtonClick") }

function OKButtonClick() { console.log("OKButtonClick") }

function OnlineRegistrationButtonClick() { console.log("OnlineRegistrationButtonClick") }
